const String kdescription =  "Hello, I am an iOS developer in unthinkable solutions. I have completed my schooling from CMS, Lucknow and currently I am pursuing B Tech from Psit, Kanpur. I love to play games which helps in increasing my skills. I also love to listen soft music.";
const String kname = "Ayush Gaur";
const String kdev = "App Developer";
const String kschool = "City Montessori School, Lucknow";
const String kcllg = "Pranveer Singh Institute of Technology, Kanpur";
const String kmailid = "ayushgaur0423@gmail.com";
const String kcontact = "+91-8887418075";
const String kloc = "Lucknow, Uttar-Pradesh, India";
const String follow = "Follow Me-";